name: wallmuse
description: "WallMuse - Beautiful wallpapers for your device"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP Client
  dio: ^5.4.0
  
  # Image Handling
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4
  path_provider: ^2.1.2
  
  # Permissions
  permission_handler: ^12.0.0+1
  
  # Utils
  intl: ^0.20.2
  logger: ^2.0.2+1
  equatable: ^2.0.5
  
  # Animation
  lottie: ^3.3.1
  shimmer: ^3.0.0
  
  # Responsive
  flutter_screenutil: ^5.9.0
  
  # Routing
  go_router: ^15.2.4
  
  # Navigation
  google_nav_bar: ^5.0.6
  flutter_animate: ^4.5.2
  curved_navigation_bar: ^1.0.6
  glassmorphism: ^3.0.0

  # Firebase - Temporarily disabled for iOS build
  # firebase_core: ^3.2.0
  # cloud_firestore: ^5.1.0
  # firebase_auth: ^5.0.0
  
  # Cloudinary
  cloudinary_public: ^0.21.0
  
  # Local Storage and Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.2.1
  media_store_plus: ^0.1.3

  # New dependency
  # gallery_saver: 2.0.1

  # Added from the code block
  url_launcher: ^6.2.6

  # Remove old gallery/image_gallery_saver dependencies
  # gallery_saver: ...
  # image_gallery_saver: ...
  gal: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - icon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png"
  remove_alpha_ios: true
