// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vymcwy8-Ew7oTYfBAzdj6PadMQ42H7Q',
    appId: '1:488554890675:web:29daafd3ee0045de7bb7c6',
    messagingSenderId: '488554890675',
    projectId: 'wallpaper-97727',
    authDomain: 'wallpaper-97727.firebaseapp.com',
    storageBucket: 'wallpaper-97727.firebasestorage.app',
    measurementId: 'G-CP14XWBR9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vymcwy8-Ew7oTYfBAzdj6PadMQ42H7Q',
    appId: '1:488554890675:android:29daafd3ee0045de7bb7c6',
    messagingSenderId: '488554890675',
    projectId: 'wallpaper-97727',
    storageBucket: 'wallpaper-97727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vymcwy8-Ew7oTYfBAzdj6PadMQ42H7Q',
    appId: '1:488554890675:ios:29daafd3ee0045de7bb7c6',
    messagingSenderId: '488554890675',
    projectId: 'wallpaper-97727',
    storageBucket: 'wallpaper-97727.firebasestorage.app',
    iosClientId: '488554890675-29daafd3ee0045de7bb7c6.apps.googleusercontent.com',
    iosBundleId: 'com.pixsbliss.app.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2vymcwy8-Ew7oTYfBAzdj6PadMQ42H7Q',
    appId: '1:488554890675:macos:29daafd3ee0045de7bb7c6',
    messagingSenderId: '488554890675',
    projectId: 'wallpaper-97727',
    storageBucket: 'wallpaper-97727.firebasestorage.app',
    iosClientId: '488554890675-29daafd3ee0045de7bb7c6.apps.googleusercontent.com',
    iosBundleId: 'com.pixsbliss.app.mobileApp',
  );
} 