name: "🍏 Build & Upload IPA"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.1)'
        required: true

jobs:
  ios-build:
    name: "🍏 iOS Build"
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.5'

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install dependencies
        run: flutter pub get

      - name: Clean CocoaPods cache
        run: pod cache clean --all

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod update

      - name: Clean build cache
        run: flutter clean

      - name: Build IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ipa/*.ipa
          asset_name: PixsBliss.ipa
          tag: ${{ github.event.inputs.tag }}
          overwrite: true 