name: "🍎 Build & Upload IPA"

on:
  workflow_dispatch:

jobs:
  ios-build:
    name: "🎉 iOS Build"
    runs-on: macos-latest
    env:
      FLUTTER_VERSION: "3.32.5"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Clean and install iOS dependencies
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install

      - name: Build release IPA (unsigned)
        run: |
          flutter clean
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../PixsBliss.ipa Payload

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: PixsBliss.ipa
          asset_name: PixsBliss.ipa
          tag: v1.0
          overwrite: true 